---
# prepare hosts
- hosts: docker_nodes, cardano_producer_nodes, cardano_relay_nodes
  become: yes
  
  var_files:
    - variables-encrypted.yml
  vars:
    - cardano_username: "cardano"
    - cardano_usergroups: "sudo"
    - enable_sshkey: true
    - cardano_ssh_pub_key_file: ~/.ssh/cardano.pub

  tasks:

    - name: Create account for cardano
      block:

        - name: "Prompt for cardano account password"
          pause:
            prompt: "Please enter password for cardano account"
            echo: yes
          register: cardano_password
            
        - name: Create cardano account
          tags: create-cardano-account
          ansible.builtin.user:
            name: "{{ cardano_username }}"
            groups: "{{ cardano_usergroups }}"
            password: "{{ cardano_password.user_input | string | password_hash('sha512') }}"
            update_password: on_create
            state: present
            create_home: yes
            shell: /bin/bash

        - name: Deploy SSH Key
          become: no
          tags: deploy-ssh-key
          authorized_key:
            user: "{{ cardano_username }}"
            key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/cardano.pub') }}"
            state: present
          when: enable_sshkey