cardano_dependencies_ubuntu:
  - automake
  - build-essential
  - pkg-config
  - libffi-dev
  - libgmp-dev
  - libssl-dev
  - libtinfo-dev
  - libsystemd-dev
  - zlib1g-dev
  - make
  - g++
  - tmux
  - git
  - jq
  - wget
  - libncursesw5
  - libtool
  - autoconf