cardano_dependencies_ubuntu:
  - automake
  - build-essential
  - pkg-config
  - libffi-dev
  - libgmp-dev
  - libssl-dev
  - libtinfo-dev
  - libsystemd-dev
  - zlib1g-dev
  - make
  - g++
  - tmux
  - git
  - jq
  - wget
  - libncursesw5
  - libtool
  - autoconf

cabal_download_url: "https://downloads.haskell.org/~cabal/cabal-install-3.2.0.0/cabal-install-3.2.0.0-x86_64-unknown-linux.tar.xz"