- name: Install Cardano Dependencies
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop: "{{ cardano_dependencies_ubuntu }}"

- name: Download, unpack, and install Cabal
  become: no
  block:
    - name: Make directory for Cabal download
      ansible.builtin.file:
        path: ~/files
        state: directory
  
    - name: Download Cabal installation archive
      ansible.builtin.get_url:
        url: "{{ cabal_download_url }}"
        dest: ~/files/cabal_installation.tar.xz

    - name: Unpack Cabal installation file
      ansible.builtin.unarchive:
        src: ~/files/cabal_installation.tar.xz
        dest: ~/files

    - name: Remove Cabal installation archive
      ansible.builtin.file:
        path: ~/files/cabal_installation.tar.xz
        state: absent

    - name: Create local bin directory
      ansible.builtin.file:
        path: ~/.local/bin
        state: directory

    - name: Copy cabal binary to local bin directory
      ansible.builtin.copy:
        src: ~/files/cabal
        dest: ~/.local/bin
        remote_src: yes
        mode: 0700
